spring:
  profiles:
    active:
    - dev
  application:
    name: microservicecloud-zuul-gateway
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dev 
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-test     